### ISSUE TITLE
Plugin not being loaded

### ISSUE THREAD

**Issue by sparcut** [EliverLara/terminator-themes#1]
File in correct location (`~/.config/terminator/plugins/`), but it does not appear in plugins panel.

I have tried reloading terminator, no luck.

Terminator Verison: 1.90

![Terminator preferences screenshot](https://user-images.githubusercontent.com/16233822/31053963-deb8ec98-a6f3-11e7-8a28-df593e413f43.png)

**Comment by EliverLara** [comment]
Hi, I would like to know two things:
* Did you install the request package? `pip install requests`.
* Did you restart terminator?

**Comment by sparcut** [comment]
@EliverLara I'm so sorry, I totally missed the first step about installing requests.

I feel so stupid, sorry for wasting your time!

**Comment by mateusdeap** [comment]
Hi there! I`m having the same issue. I have requests installed, have reloaded my terminal and even logged out of my computer and logged in, but to no effect...

**Comment by EliverLara** [comment]
Hi, did you download the right plugin for your terminator version? if so, could you please provide a screenshot showing the result of running terminator from a terminal?

**Comment by EliverLara** [comment]
Thanks, can you tell me what's your python version please?

**Comment by mateusdeap** [comment]
I installed using python 3.6. Although the computer has 2.7 on it. But I ran the commands using "$ python3 <options, etc>"

**Comment by mateusdeap** [comment]
To be honest, I only had to update pip, when I ran pip install requests it said requirement was already satisfied, thusly:
![screenshot at 2018-04-05 22-58-49](https://user-images.githubusercontent.com/14188887/38400153-fb59ee2e-3924-11e8-8f1c-028f336e7f2f.png)

**Comment by EliverLara** [comment]
Thanks! Checkout the issue #3 I think that will solve your problem.

**Comment by mateusdeap** [comment]
Thank you very much! It worked nicely!
