### ISSUE TITLE
Having problem when loading the plugin in ubuntu 16.04

### ISSUE THREAD

**Issue by timothyleung** [EliverLara/terminator-themes#10]
`** (terminator:6508): WARNING **: Binding '<Shift><Control><Alt>a' failed!
Unable to bind hide_window key, another instance/window has it.
PluginRegistry::load_plugins: Importing plugin __init__.py failed: 'module' object has no attribute 'AVAILABLE'
PluginRegistry::load_plugins: Importing plugin terminator-themes.py failed: When using gi.repository you must not import static modules like "gobject". Please change all occurrences of "import gobject" to "from gi.repository import GObject". See: https://bugzilla.gnome.org/show_bug.cgi?id=709183
`

**Comment by timothyleung** [comment]
Not sure if it is dependency issue in Ubuntu.

**Comment by EliverLara** [comment]
Hi, did you download the correct plugin for your terminator version?

**Comment by timothyleung** [comment]
OOpps, my bad. I assumed I have the latest version coz I just apt install yesterday. It is 0.98.. 

Thanks for the great plugin!
