### ISSUE TITLE
Theme not Working on Split view

### ISSUE THREAD

**Issue by ejabu** [EliverLara/terminator-themes#16]
![screenshot_20180629_111950](https://user-images.githubusercontent.com/2019630/42073053-78fa8342-7b8e-11e8-9d71-d26a69252aea.png)

After split horizontally, theme is not working again.

Using Kubuntu 18.04 , KDE Plasma

**Comment by EliverLara** [comment]
Hi, that's because the plugin only installs the theme and does not define it as default, so check #8 to define it as default and thus be able to reuse it in each instance of terminator.

**Comment by ejabu** [comment]
Finally I figured it out by editing config file manually. 

Great support !

Thanks a lot. I will dump Tilix, and Yakuake, then
