### ISSUE TITLE
ERROR 503: Service Unavailable - This page isn’t working

### ISSUE THREAD

**Issue by d3vCr0w** [EliverLara/terminator-themes#19]
Hi, it seems like https://git.io/v5Zww and https://git.io/v5Zwz are not working, I always get HTTP ERROR 503.

**Comment by EliverLara** [comment]
Hi, links are wornking perfectly

![terminator](https://user-images.githubusercontent.com/9838260/45046006-773edb80-b03a-11e8-8c92-47a2a7a0cd99.png)
