### ISSUE TITLE
how to use int with Linux Ubuntu 

### ISSUE THREAD

**Issue by ahmadRagheb** [EliverLara/terminator-themes#2]
hi  i love the themes but idk how to install it to ubuntu  wget https://git.io/v5Zwz -O $HOME"/.config/terminator/plugins/terminator-themes.py"

**Comment by EliverLara** [comment]
Hi, what is the problem when running the command?

**Comment by ahmadRagheb** [comment]
i solve it , the error was i don't have ~/.config/terminator/plugins  file 
here is the answers 
https://askubuntu.com/questions/700015/set-path-for-terminator-to-lookup-for-plugins/700023#700023?newreg=c5ded80617044827a687f81cdcc0a32c
