### ISSUE TITLE
Bad Solarized colors?

### ISSUE THREAD

**Issue by roipoussiere** [EliverLara/terminator-themes#24]
If I look at the [Solarized color scheme page](https://ethanschoonover.com/solarized/), I can find these color codes:

SOLARIZED | HEX  |   16/8 | TERMCOL
--------- | ------- | ---- | -------
base03  |  #002b36 |  8/4 | brblack
base02 |    #073642 |  0/4 | black
base01   |  #586e75 | 10/7 | brgreen
base00  |   #657b83 | 11/7 | bryellow
base0  |    #839496 | 12/6 | brblue
base1    |  #93a1a1 | 14/4 | brcyan
base2  |    #eee8d5 |  7/7 | white
base3  |    #fdf6e3 | 15/7 | brwhite
yellow |   #b58900 |  3/3 | yellow
orange  |   #cb4b16 |  9/3 | brred
red  |      #dc322f | 1/1 | red
magenta |   #d33682 |  5/5 | magenta
violet   |  #6c71c4 | 13/5 | brmagenta
blue    |   #268bd2 |  4/4 | blue
cyan |      #2aa198 |  6/6 | cyan
green  |    #859900  | 2/2 | green

That does not fit with the terminator configs in this repo:

## Solarized Darcula

    palette = "#25292a:#f24840:#629655:#b68800:#2075c7:#797fd4:#15968d:#d2d8d9:#25292a:#f24840:#629655:#b68800:#2075c7:#797fd4:#15968d:#d2d8d9"
    background_color = "#3d3f41"
    cursor_color = "#708284"
    foreground_color = "#d2d8d9"

## Solarized Dark - Patched

    palette = "#002831:#d11c24:#738a05:#a57706:#2176c7:#c61c6f:#259286:#eae3cb:#475b62:#bd3613:#475b62:#536870:#708284:#5956ba:#819090:#fcf4dc"
    background_color = "#001e27"
    cursor_color = "#708284"
    foreground_color = "#708284"

## Solarized Dark Higher Contrast

    palette = "#002831:#d11c24:#6cbe6c:#a57706:#2176c7:#c61c6f:#259286:#eae3cb:#006488:#f5163b:#51ef84:#b27e28:#178ec8:#e24d8e:#00b39e:#fcf4dc"
    background_color = "#001e27"
    cursor_color = "#f34b00"
    foreground_color = "#9cc2c3"

## Solarized Dark

    palette = "#002831:#d11c24:#738a05:#a57706:#2176c7:#c61c6f:#259286:#eae3cb:#001e27:#bd3613:#475b62:#536870:#708284:#5956ba:#819090:#fcf4dc"
    background_color = "#001e27"
    cursor_color = "#708284"
    foreground_color = "#708284"

Why?

**Comment by EliverLara** [comment]
I've updated the wrong colors, thanks!
