### ISSUE TITLE
Splitting a window adds a terminal with the standard theme

### ISSUE THREAD

**Issue by lverona** [EliverLara/terminator-themes#25]
I have applied the themes and then set the default theme in the layout. However, this only works for the first window. All subsequent windows, formed out of splits, are opening with the default theme.

Part of the beauty of the Terminator is that I don't have a fixed layout. So, is there a way to just always apply a chosen theme to any of the new splits?

**Comment by EliverLara** [comment]
Hi, please check #8, I think that's what you're looking for

**Comment by lverona** [comment]
@EliverLara Thank you very much! This worked!

I think this might be a very typical question. Do you think it makes sense to add this to the description on the main page?

**Comment by lverona** [comment]
I mean specifically this part:

Under the [global config] section, set
always_split_with_profile = True
in the config file ~/.config/terminator/config

**Comment by graceman9** [comment]
@EliverLara Why not to add this "always_split_with_profile = True" part into the **Setting a Default** section?

**Comment by EliverLara** [comment]
Instructions were added to readme, thanks!.
