### ISSUE TITLE
No Themes in context menu

### ISSUE THREAD

**Issue by intrudir** [EliverLara/terminator-themes#28]
Hi, I'm in a fresh install of terminator, installed and activated TerminatorThemes in the plugin menu but no Themes in context menu to install themes. There an alternate way of installing the themes for now?

**Comment by EliverLara** [comment]
Hi, did you try restarting terminator?

**Comment by intrudir** [comment]
Yep, reinstalled, rebooted, redid my OS = nada :(. What kind of logs can I provide you with to help figure this out? Im running latest release of kali.

**Comment by EliverLara** [comment]
Please provide your terminator version, also run terminator from another terminal and paste the output here

**Comment by k1-k0** [comment]
@intrudir Hello. I had same problem, but that comment helped me and you could try that approach: 
https://github.com/EliverLara/terminator-themes/issues/14#issuecomment-405139189

**Comment by sbuvaneshkumar** [comment]
Initially I don't find the plugin listed in plugins option.
But after following #14 , I resolved this problem.

However, I don't see any themes as like mentioned in this issuel,
```
அ  ~  terminator --version
terminator 1.91
```

**Comment by EliverLara** [comment]
> Please provide your terminator version, also run terminator from another terminal and paste the output here

Could you do that please?

**Comment by sbuvaneshkumar** [comment]
@EliverLara Sure.
```
அ  ~  terminator --version                 
terminator 1.91

அ  ~  terminator          
** (terminator:7332): WARNING **: 09:40:25.357: Binding '<Control><Alt>a' failed!
Unable to bind hide_window key, another instance/window has it.
```
However, I can be able to see that there is an another terminator launched.
![image](https://user-images.githubusercontent.com/12863319/71706890-5d1f3400-2e0d-11ea-920a-d1dcce8bffc2.png)

**Comment by sbuvaneshkumar** [comment]
Update: I have closed all the other terminator windows, after that I don't get the error now.
This time, I have launched the terminator via gnome-terminal.
![image](https://user-images.githubusercontent.com/12863319/71707035-bb4c1700-2e0d-11ea-9bc9-9efa86a74d14.png)
And the issue persists.
![image](https://user-images.githubusercontent.com/12863319/71707053-d454c800-2e0d-11ea-98b7-d11abc15af6e.png)

**Comment by EliverLara** [comment]
@sbuvaneshkumar  it seems that there are no errors when loading the plugin, so you should be able to right click on the terminator window and select 'themes'

**Comment by tcoker** [comment]
I have the same issue, no themes option in context menu, no way to install themes in preferences. Terminator 1.91.

**Comment by sbuvaneshkumar** [comment]
@EliverLara I can confirm that it is working for me. Thanks!

**Comment by tcoker** [comment]
Figured out what my problem was, working correctly now.

**Comment by pide2000** [comment]
> Figured out what my problem was, working correctly now.

Maybe you can tell us what you've done? I have the sam issue. 

Thank you

**Comment by kalimbra** [comment]
> > Figured out what my problem was, working correctly now.
> 
> Maybe you can tell us what you've done? I have the sam issue.
> 
> Thank you

Same here. I have look in terminator/config, and for a gi.repository without success
