### ISSUE TITLE
Problem with fetching the theme list

### ISSUE THREAD

**Issue by poooyak** [EliverLara/terminator-themes#29]
Hi,

I just installed this plugin and when I want to use it, it gives me "Failed to get list of available themes".
After I dug into the code and checked the base URL on the browser it shows me: 
`{
"message": "API rate limit exceeded for 216.228.112.22. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)",
"documentation_url": "https://developer.github.com/v3/#rate-limiting"
}`

**Comment by EliverLara** [comment]
Hi, Does this still persist?

**Comment by poooyak** [comment]
No it got fixed thanks.
