### ISSUE TITLE
Plugin not detected

### ISSUE THREAD

**Issue by argentum47** [EliverLara/terminator-themes#3]
I am running terminator 1.91 on archlinux. python version is 3.6. I (sudo) pip installed requests. ran the first wget command. closed and reopened terminator. the terminator-themes.pyc is generated but doesn't show up in plugins.

**Comment by erichall** [comment]
Same system and same problem.

**Comment by EliverLara** [comment]
Hi, could you run terminator from the CLI and paste the output here? Please.

**Comment by gallaharsha** [comment]
I have the same issues, I get the these errors:
PluginRegistry::load_plugins: Importing plugin __init__.py failed: 'module' object has no attribute 'AVAILABLE'
PluginRegistry::load_plugins: Importing plugin terminator-themes.py failed: No module named requests

I do have requests installed, not sure why this complains.

Thanks.

**Comment by EliverLara** [comment]
Thanks for the info @gallaharsha, terminator works with python 2, so assuming you are using python 3 you must install the `python2-requests` ( `pacman -S python2-requests` )  package instead of the default command `pip install requests`.

**Comment by ilazaridis** [comment]
Thanks @EliverLara, it would be really helpful to update readme accordingly. :)
