### ISSUE TITLE
Theme fails to install

### ISSUE THREAD

**Issue by psalm52** [EliverLara/terminator-themes#46]
Hi when I try to install a theme i get the following error.
/.config/terminator/plugins/terminator-themes.py", line 253, in on_install
    self.terminal.config.add_profile(target["name"]) 
TypeError: Config.add_profile() missing 1 required positional argument: 'toclone'

terminator 2.1.2

**Comment by EliverLara** [comment]
Fixed with [2daa15e](https://github.com/EliverLara/terminator-themes/commit/2daa15e01e6cb3abd6535c2d4b7727b8eaf18b77) :)
