### ISSUE TITLE
Is it possible somehow to set a default theme?

### ISSUE THREAD

**Issue by nicktobolski** [EliverLara/terminator-themes#8]
I don't enjoy selecting a theme every time I open a new tab or a window.

**Comment by jacsmith21** [comment]
I just figured out how to do this. Basically once you install a theme it's stored in `Preferences` > `Profiles`. To change an installed theme to the default one open `~/.config/terminator/config` and replace the `[[default]]` theme with your preferred theme under the `[profiles]` setting. Does that work?

**Comment by EliverLara** [comment]
Hi @nicktobolski the solution proposed by @jacsmith21  is correct and it works, but if you do not want to deal with the modification of the configuration file, you can do the following:

1. Go to `Preferences`
2. Choose the `Layouts` tab.
3. Choose your preferred layout.
4. Choose the layout terminal (in the next column)
5. Choose you preferred profile

![captura de pantalla de 2018-03-08 22-56-33](https://user-images.githubusercontent.com/9838260/37191250-078e1042-2324-11e8-9d57-a726b157ccef.png)

**Comment by nicktobolski** [comment]
Thank you for your help, gentlemen. I've made a PR that should help avoid this question the future: https://github.com/EliverLara/terminator-themes/pull/9

**Comment by sayoojsamuel** [comment]
Under the [global config]  section, set
>always_split_with_profile = True
in the config file **~/.config/terminator/config**
